version: '3.8'

services:
  neo4j_7db:
    container_name: neo4j_7db
    image: neo4j:5.22.0
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo4j_7db_data:/data

volumes:
  neo4j_7db_data: