version: '3.8'

services:
  configsvr1:
    image: mongo:4.4
    command: mongod --replSet configReplSet --configsvr --port 27019
    container_name: configsvr1
    ports:
      - 27019:27019
    volumes:
      - config1:/data/db
    networks:
      - sharding1

  configsvr2:
    image: mongo:4.4
    command: mongod --replSet configReplSet --configsvr --port 27019
    container_name: configsvr2
    ports:
      - 27020:27019
    volumes:
      - config2:/data/db
    networks:
      - sharding1

  configsvr3:
    image: mongo:4.4
    command: mongod --replSet configReplSet --configsvr --port 27019
    container_name: configsvr3
    ports:
      - 27021:27019
    volumes:
      - config3:/data/db
    networks:
      - sharding1

  shard1svr1:
    image: mongo:4.4
    command: mongod --shardsvr --replSet shard1 --port 27018
    container_name: shard1svr1
    ports:
      - 27018:27018
    volumes:
      - shard1-1:/data/db
    networks:
      - sharding1

  shard1svr2:
    image: mongo:4.4
    command: mongod --shardsvr --replSet shard1 --port 27018
    container_name: shard1svr2
    ports:
      - 27022:27018
    volumes:
      - shard1-2:/data/db
    networks:
      - sharding1

  shard1svr3:
    image: mongo:4.4
    command: mongod --shardsvr --replSet shard1 --port 27018
    container_name: shard1svr3
    ports:
      - 27023:27018
    volumes:
      - shard1-3:/data/db
    networks:
      - sharding1

  shard2svr1:
    image: mongo:4.4
    command: mongod --shardsvr --replSet shard2 --port 27018
    container_name: shard2svr1
    ports:
      - 27024:27018
    volumes:
      - shard2-1:/data/db
    networks:
      - sharding1

  shard2svr2:
    image: mongo:4.4
    command: mongod --shardsvr --replSet shard2 --port 27018
    container_name: shard2svr2
    ports:
      - 27025:27018
    volumes:
      - shard2-2:/data/db
    networks:
      - sharding1

  shard2svr3:
    image: mongo:4.4
    command: mongod --shardsvr --replSet shard2 --port 27018
    container_name: shard2svr3
    ports:
      - 27026:27018
    volumes:
      - shard2-3:/data/db
    networks:
      - sharding1

  mongos:
    image: mongo:4.4
    command: mongos --configdb configReplSet/configsvr1:27019,configsvr2:27019,configsvr3:27019
    container_name: mongos
    ports:
      - 27017:27017
    networks:
      - sharding1

volumes:
  config1:
  config2:
  config3:
  shard1-1:
  shard1-2:
  shard1-3:
  shard2-1:
  shard2-2:
  shard2-3:

networks:
  sharding1:
    driver: bridge
